# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key', models.TextField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
